# Generated by Django 4.2.2 on 2024-08-01 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Что вы будете делать', max_length=250, verbose_name='Действие')),
                ('place', models.CharField(max_length=250, verbose_name='Где Вы будете делать')),
                ('time', models.TimeField(default='18:13')),
                ('is_pleasant', models.BooleanField(verbose_name='отметка для приятной привычки')),
                ('period', models.CharField(choices=[('once', 'Единожды'), ('every_day', 'Ежедневно'), ('every_week', 'Еженедельно'), ('every_month', 'Ежемесячно')], default='once', help_text='Периодичность', max_length=100, verbose_name='Периодичность')),
                ('prize', models.CharField(help_text='Награда за соблюдение', max_length=250, verbose_name='Награда')),
                ('time_to_do', models.TimeField(help_text='время на выполнение', verbose_name='Время на выполнение привычки')),
                ('is_published', models.BooleanField(verbose_name='Публичность')),
                ('associated_habit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit')),
            ],
            options={
                'verbose_name': 'Попытка',
                'verbose_name_plural': 'Попытки',
            },
        ),
    ]
