# Generated by Django 4.2.2 on 2024-08-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_alter_habit_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='next_day_to_do',
            field=models.DateField(blank=True, null=True, verbose_name='день выполнения'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='period',
            field=models.CharField(choices=[('every_day', 'Ежедневно'), ('every_week', 'Еженедельно')], default='every_day', help_text='Периодичность', max_length=100, verbose_name='Периодичность'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.TimeField(default='33:31'),
        ),
    ]
